### ISSUE TITLE
Problems installing abSimSeq

### ISSUE THREAD

**Issue by Glfrey** [warrenmcg/absSimSeq#1]
Hi there,

When using githubinstall("absSimSeq") I'm receiving the following errors:
Skipping 6 packages not available: biomaRt, Biostrings, DESeq2, polyester, sleuth, sleuthALR
Installing 3 packages: sleuth, sleuthALR, vctrs
Error: Failed to install 'absSimSeq' from GitHub:
  (converted from warning) packages ‘sleuth’, ‘sleuthALR’ are not available (for R version 3.6.1)
In addition: Warning message:
In fread(download_url, sep = "\t", header = FALSE, stringsAsFactors = FALSE,  :
  Found and resolved improper quoting out-of-sample. First healed line 4848: <<Puriney	honfleuR	"Evening, honfleuR" by Seurat>>. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.

I tried another way and also got an error message: devtools::install_github('warrenmcg/absSimSeq')

✔  checking for file ‘/private/var/folders/7j/1mwnwkx56fbcn2kfl4dymtwc0000gn/T/RtmpakIkFu/remotes92877102c3db/warrenmcg-absSimSeq-c68410f/DESCRIPTION’ ...
─  preparing ‘absSimSeq’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘absSimSeq_0.0.0.9000.tar.gz’

   
ERROR: dependencies ‘sleuth’, ‘sleuthALR’ are not available for package ‘absSimSeq’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/absSimSeq’
Error: Failed to install 'absSimSeq' from GitHub:
  (converted from warning) installation of package ‘/var/folders/7j/1mwnwkx56fbcn2kfl4dymtwc0000gn/T//RtmpakIkFu/file92876c8898d3/absSimSeq_0.0.0.9000.tar.gz’ had non-zero exit status

I'd be grateful for some insight into how I can get the package installed, thank you!

**Comment by warrenmcg** [comment]
Hi @Glfrey,

Thanks for using the tool! The package requires the [`sleuth`](https://github.com/pachterlab/sleuth) and the [`sleuth-ALR`](https://github.com/warrenmcg/sleuth-ALR) packages, both of which are also on GitHub. I have not figured out how to have those dependencies automatically checked and installed for users not used to these error messages. This is reminding me that I should update the installation instructions to have these installed first.

Let me know if you still have trouble installing after installing these other packages.

**Comment by Glfrey** [comment]
Hi @warrenmcg  thank you so much for your rapid reply and for creating the tool! I really enjoyed your paper "Compositional Data Analysis is necessary for simulating and analyzing RNA-Seq data" and have just used polyester for some RNA-Seq simulation so I'm excited to try this out!

**Comment by warrenmcg** [comment]
Excellent! Feel free to provide any additional feedback once you starting using it!
